### ISSUE TITLE
README 里建议添加 DanmakuFactory 赋予运行权限 说明

### ISSUE THREAD

**Issue by ResidualBlood** [hechuan4/BiliFavoritesDownloader#2]
git 下来的 `DanmakuFactory` 没有运行给运行权限， 移动到 `bili-cookies` 后会报 `./bilidown-lux.sh: line 121: /mnt/BiliFavoritesDownloader/bili-cookies/DanmakuFactory: Permission denied`
加个 `chmod +x DanmakuFactory` 就好了

另外为什么不直接放到 `/bili-cookies` 里呢？

**Comment by ResidualBlood** [comment]
`bilidown-lux.sh` 同理

**Comment by hechuan4** [comment]
那你就得问原作者了:https://github.com/Left024/BiliFavoritesDownloader

我只替换了[you-get](https://github.com/soimort/you-get)下载为[lux](https://github.com/iawia002/lux)下载而已.

**Comment by ResidualBlood** [comment]
好的嘛

**Comment by ResidualBlood** [comment]
git clone 下原作者仓库， 也是都没有 运行权限， 可能是 https clone 的原因？
另外 `DanmakuFactory` 为什么不直接放到 `/bili-cookies` 里呢？

**Comment by hechuan4** [comment]
不是,
就是运行权限的问题.
`chmod +x `
`DanmakuFactory`这个文件,原仓库就在外面,我也就放外面了...

**Comment by ResidualBlood** [comment]
emmn， 建议直接放 `bili-cookies` 吧

**Comment by hechuan4** [comment]
行!
