### ISSUE TITLE
报错{"ok":false,"error_code":404,"description":"Not Found"}，请问大佬脚本现在还可以使用吗

### ISSUE THREAD

**Issue by TimingBule** [hechuan4/BiliFavoritesDownloader#3]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/88302654/228748213-60040d7d-4713-48a4-b60e-51e045462319.png">

**Comment by hechuan4** [comment]
可以用,ubuntu18-20都测试过.
检查不出问题,可以去tg发我.

**Comment by Jue-Xu** [comment]
我目前使用也都正常

**Comment by TimingBule** [comment]
问题已解决，文件权限和cookies问题。感谢博主的帮助，~祝您工作顺利，生活愉快！
