### ISSUE TITLE
Rsshub UP 主投稿 路由 反爬严格

### ISSUE THREAD

**Issue by Jue-Xu** [hechuan4/BiliFavoritesDownloader#5]
如题 https://docs.rsshub.app/routes/social-media#bilibili-up-zhu-tou-gao
是否 考虑用 [UP 主动态](https://docs.rsshub.app/routes/social-media#bilibili-up-zhu-dong-tai)路由作为代替？

**Comment by Jue-Xu** [comment]
写了个简陋的实现：

首先，路由
`bilidown-lux.sh "user/video" "35847683" "0" "峰哥亡命天涯"`
改成
`bilidown-lux.sh "user/dynamic" "35847683" "0" "峰哥亡命天涯"`

另外，改连接获取
`link=${sublink%%</link>*}`
改成
```
if [ "$1" = "user/dynamic" ]; then
    link=$(echo $content | grep -o 'https://www.bilibili.com/video/[^>"]*' | head -n 1)
    echo 'using user/dynamic'
    echo $link
else
    link=${sublink%%</link>*}
    #echo $link
fi
```

这样有个问题，会把up主动态转发的视频也下载下来，不过对我个人来说问题不大

**Comment by hechuan4** [comment]
确实不错，这样改是下载某位up主的更新投稿了吗？
收藏夹的还能下吗。

**Comment by Jue-Xu** [comment]
这样是把 下载 `up主的最新投稿` 改成 `up主的最新动态包含的视频`。

收藏夹完全不影响，如果 `"$1" != "user/dynamic"`，还是用原来的逻辑。

PS. 感觉最近的 UP主投稿 路由 反爬严格了很多
